name: CommitSolution

on:
  repository_dispatch:
    types: [commitSolutionToRepo]
    
env:
#edit your values here
  ENVIRONMENT_URL: 'https://org84e5d14c.crm4.dynamics.com'
  TENANT_ID: 8e3ece52-5ce7-40a6-b095-3398c5ed05ba
  solution_exported_folder: 'out/exported/'
  solution_folder: 'out/solutions/'
  solution_target_folder: 'solutions/'
  solution_name: ${{ github.event.client_payload.solutionName }}

jobs:
  export-from-dev:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{ secrets.APP_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{ secrets.APP_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ env.solution_name }}
        solution-output-file: ${{ env.solution_exported_folder }}/${{ env.solution_name }}.zip
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ env.solution_exported_folder }}/${{ env.solution_name }}.zip
        solution-folder: ${{ env.solution_folder }}/${{ env.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true
        process-canvas-apps : true 
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ env.solution_folder }}/${{ env.solution_name }}
        solution-target-folder: ${{ env.solution_target_folder }}/${{ env.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true