name: CommitSolution

on:
  repository_dispatch:
    types: [commitSolutionToRepo]
    
env:
#edit your values here
  ENVIRONMENT_URL: 'https://org84e5d14c.crm4.dynamics.com'
  TENANT_ID: 8e3ece52-5ce7-40a6-b095-3398c5ed05ba
  solution_exported_folder: 'out/exported/'
  solution_folder: 'out/solutions/'
  solution_target_folder: 'solutions/'
  solution_name: ${{ github.event.client_payload.solutionName }}

jobs:
  export-from-dev:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org84e5d14c.crm4.dynamics.com'
        app-id: '74d0e8c5-b814-4bb8-9fd4-6cd0578a60e4'
        client-secret: 'U5p8Q~XU1vBdpO_hlTZkQkgcUH~5gbH-C4EBTa8C'
        tenant-id: '8e3ece52-5ce7-40a6-b095-3398c5ed05ba'
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip




    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true




    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
