name: CreateRelease

on:
  repository_dispatch:
    types: [prepareRelease]
    
env:
  #edit your values here
  solution_target_folder: 'solutions/'
  solution_name: ${{ github.event.client_payload.solutionName }}
  solution_release_folder: 'release/'
  solution_shipping_folder: 'out/'

jobs:
  prepare_assets:
    runs-on: windows-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{ env.solution_target_folder }}/${{ env.solution_name }}
        solution-file: ${{ env.solution_shipping_folder }}/${{ env.solution_name }}.zip
        solution-type: Unmanaged

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ env.solution_shipping_folder}}/${{ env.solution_name }}.zip

  create_release:
    needs: [ prepare_assets ]
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{ env.solution_release_folder}}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        name: Release for {{ env.solution_name }}
        files: ${{ env.solution_release_folder}}/*
