name: CreateRelease

on:
  repository_dispatch:
    types: [prepareRelease]
    
env:
  #edit your values here
  solution_target_folder: 'solutions/'
  solution_name: ${{ github.event.client_payload.solutionName }}
  solution_release_folder: 'release/'
  solution_shipping_folder: 'out/'
  TEST_ENVIRONMENT_URL: 'https://orgecdc3b0b.crm4.dynamics.com'
  TENANT_ID: 8e3ece52-5ce7-40a6-b095-3398c5ed05ba

jobs:
  prepare_assets:
    runs-on: windows-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{ env.solution_target_folder }}/${{ env.solution_name }}
        solution-file: ${{ env.solution_shipping_folder }}/${{ env.solution_name }}.zip
        solution-type: Unmanaged

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ env.solution_shipping_folder}}/${{ env.solution_name }}.zip

  create_release:
    needs: [ prepare_assets ]
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{ env.solution_release_folder}}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        name: Release for ${{ env.solution_name }}
        generate_release_notes: true
        files: ${{ env.solution_release_folder}}/*

  deploy_solution:
    needs: [ create_release ]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{ inputs.solution_release_folder}}

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.TEST_ENVIRONMENT_URL}}
        app-id: ${{ secrets.APP_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ inputs.solution_release_folder}}/${{ inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true